----------------------------------------
Installation + Official Docs
----------------------------------------
https://reactnative.dev/docs/environment-setup?guide=native 
https://reactnative.dev/

npx react-native@latest init AwesomeProject [folder name] && code . 
npm run start && npm run android

Android Studio Setup - Emulator  
https://www.youtube.com/watch?v=r33OwlTnTE4 
SDK manager -> SDK Platforms > Android 13 tick && SDK Tools > 31.0.0 tick > Apply.
Virtual Device Manager > Create Device > Select Device > Recommended OS [click download] > Next > Finish > Play button in the device manager list > Android Emulator Opens. [react native code plays in Emulator]

---------------------------------------------------
Why React Native ?
---------------------------------------------------
React native can be written with Swift or Java to build react native apps
Flutter vs react native - WHY RN?
Developed by Meta in 2015 
3 main reason
- big community, enough documentation, enough solutions to issues.
- Big companies using it , used by Facebook , uber eats , skype , Shopify 
- job wise more hiring, Opening and demand is high 
- cross platform iOS & Android
- Meta so JSX + react based 
- Cross platform support
- Learning curve is low.

---------------------------------
Principle of react native code
--------------------------------
Core components & native components
Compile react native code to native code
UI user interface are views (list button image)

Example <view> <Text> - react native
Android view - viewGroup , Textvie
iOS - UiTextview , UIView

------------------------------------
4 things to do code in react native
------------------------------------
1. Import tools we need
2. Own components create
3. Fun things , style sheet is an api react gives us
4. Export - use it other components , Export is mandatory to use this code in other component
Companies using react native to build their apps like Facebook , instagram , Uber Eats , Skype , Discord

----------------------
React Native Gives
----------------------
API , Dimensions api gives user dimension using the external api
Components UI
React libraries also used in react native , React library knows what to show in UI
React native code -> convert -> Native code 

------------------------------
React native apps prerequisites
------------------------------
1. lts nodejs
2. Vs code
3. Expo command line interface
4. React native app
5. Android stimulator
6. iPhone stimulator
 
------------------------------
React Native Libraries
-------------------------------
React navigation / navigate to many pages
Firebase / authentication functionality
Stripe / Razorpay alternative
Paypal / Global payment
Google map / API to integrate maps inside apps
Css in JS 
Animate / Lote , Airbnb library
Deploy APPS
React Hooks 
Device Permission
Debugging Support

25$ One time payment for play store my Apps.

---------------------------------------
Vs Code Extension to react native app
---------------------------------------
https://youtu.be/2x8HP_VnPGc?feature=shared

-----------------------------------------------------------------------------------------------
Few Steps carried out while doing react native
-----------------------------------------------------------------------------------------------
sudo install -y , y means [automatically agree to install prompts that ask you to answer yes]
Homebrew
make --version // sudo apt install build-essential
curl - sudo apt install curl // curl --version
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

node --version && java --version -> mandate

git --version // sudo apt install git

echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/naraine/.bashrc
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
brew doctor
brew update && upgrade
brew search htop // brew install htop

nano ~/.bashrc -> Export 3 line copy from docs paste it in the last line.
source ~/.bashrc

------------------------------------------------------------------------------------------------

